"""New Migration

Revision ID: 01f749760b6a
Revises: 6f598be9dd1c
Create Date: 2023-03-22 19:45:46.339045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f749760b6a'
down_revision = '6f598be9dd1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
